### ISSUE TITLE
Unable to Input in Minibuffer

### ISSUE THREAD

**Issue by Aeres-u99** [swaroopch/rangoli-emacs#2]
**Bug:**
Unable to enter any command in `M-x` menu, Pressing same button twice is what allows entering while using `emacs-application-framework` browser.
**Expected Behaviour:**
Should be able to enter commands regardless of the buffer
**Steps to reproduce:** 
1. Install eaf
2. `M-x eaf-open-browser`
3. Enter any url
4. `M-x`
Now even while pressing the keys they wont show up in minibuffer 
Here is the video of bug:
https://imgur.com/a/JjRdXSJ

**Possible Solution:**
Disable Minibuffer plugin and check again, but sadly I don't know how to.

**Comment by swaroopch** [comment]
Hello! I have not used eaf, so am not familiar with it, nor used it. So, not sure how I can help here. Let me know if we can find anything that can be fixed inside this Emacs configuration repo specifically :-)
